In [78]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [79]:
import numpy as np

In [80]:
x=np.array([[7,8,9]])
x

array([[7, 8, 9]])

In [81]:
y=np.swapaxes(x,0,1)
y

array([[7],
       [8],
       [9]])

In [82]:
y[0,0]=10
x

array([[10,  8,  9]])

In [83]:
x= np.array(np.arange(8).reshape(2,2,2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
np.swapaxes(x,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [85]:
np.transpose(x, (2,1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [86]:
org =np.arange(5)
org

array([0, 1, 2, 3, 4])

In [87]:
v=org.view()
v

array([0, 1, 2, 3, 4])

In [88]:
v[2]=200
v

array([  0,   1, 200,   3,   4])

In [89]:
org

array([  0,   1, 200,   3,   4])

In [90]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [91]:
c=org.copy()
c

array([0, 1, 2, 3, 4])

In [92]:
c[2]=200
c

array([  0,   1, 200,   3,   4])

In [93]:
org

array([0, 1, 2, 3, 4])

In [94]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [95]:
y=x.reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
y.base 

array([0, 1, 2, 3, 4, 5])

In [97]:
z=y.transpose
z.base

AttributeError: 'builtin_function_or_method' object has no attribute 'base'

In [ ]:
c= z.copy()
print(c.base)

AttributeError: 'builtin_function_or_method' object has no attribute 'copy'

In [ ]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
lst[3:5]=[30,40,50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [ ]:
x= np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[3:5]=[30,40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [ ]:
x[3:5]=[30,40,50]
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b=a
b is a 


True

In [ ]:
print(id(a))
print(id(b))

2394515943568
2394515943568


In [ ]:
print(b.base)

None


In [ ]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [ ]:
v =a.reshape(3,2)
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [ ]:
print(id(a))
print(id(v))

2394515943568
2394515947024


In [ ]:
v[0,1]=200
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [ ]:
v.base

array([[100, 200,   3],
       [  4,   5,   6]])

In [98]:
from numpy import array

a= array([3,4,5])
b=array([8,7,6])
a*b

array([24, 28, 30])

In [99]:
from numpy import array 

a= array([3,4,5])
a

array([3, 4, 5])

In [100]:
b=2
b

2

In [101]:
a+b

array([5, 6, 7])

In [ ]:
from numpy import array
A=array([[1,2,3],[1,2,3]])
A

In [ ]:
a+2

In [ ]:
from numpy import arange

x=arange(1,10).reshape(3,3)
x

In [ ]:
y= arange(-1,2)
y

In [ ]:
x*y

In [ ]:
x+y

In [ ]:
from numpy import arange
x= arange(1,10).reshape(3,3)
x

In [ ]:
y = arange(3,10,3).reshape(3,1)
y

In [ ]:
x/y

In [ ]:
x-y

In [ ]:
from numpy import arange

x= arange(1,4)
x

In [ ]:
y= arange(1,4).reshape(3,1)
y

In [ ]:
x*y

In [ ]:
x-y

In [ ]:
from numpy import arange

x=arange(0,10,3).reshape(4,1)
x

In [ ]:
y=arange(1,3)
y

In [ ]:
x*y

In [ ]:
x+y

In [ ]:
from numpy import arange

x=array([0,10,20,30])
x

In [ ]:
a= x[np.newaxis, :]
a

In [ ]:
a=x[:, np.newaxis]
a

In [ ]:
a+b

In [ ]:
x*y

In [ ]:
x= np.arange(10)
x

In [ ]:
print(x[1])
print(x[[2,3]])

In [ ]:
x[[2,3,5,8]]

In [ ]:
x[np.array([5,3,-4,8])]

In [ ]:
x[np.array([10])]

In [ ]:
from numpy import arange

x= arange(56).reshape(7,8)
x

In [ ]:
x[0,1]

In [ ]:
x[:,2:8]

In [ ]:
x[[0],[1]]

In [ ]:
x[:, [5,4]]

In [ ]:
x[[1,3]]

In [ ]:
x[[1,3], :]

In [ ]:
x[[1,3],[2,2]]

In [ ]:
x[[1,3],[2]]

In [ ]:
x[[1,3],[3,3]]

In [ ]:
x[[1,3],[3]]

In [ ]:
from numpy import array
x[array([0,2,4]), array([0,1])]

In [ ]:
x[np.array([0,2,4]),1]

In [ ]:
print(x[0,1])
print(x[2,1])
print(x[4,1])

In [ ]:
from numpy import arange

a= arange(40).reshape(5,8)
a

In [ ]:
a[2:4, 3:7]

In [ ]:
a[arange(2,4)]

In [ ]:
a[arange(2,4)][:, [1,0]]

In [ ]:
a[arange(2,5)][:, [1,0,3,5]]

In [ ]:
a[arange(2,5)][:, arange(-1,-8,-1)]

In [ ]:
import numpy as np

a= np.arange(6).reshape(3,2)
a

In [ ]:
b=np.arange(6,12).reshape(3,2)
b

In [ ]:
np.vstack((a,b))

In [ ]:
c=np.arange(20,24).reshape(2,2)
c

In [ ]:
np.vstack((a,c))

In [ ]:
np.vstack((a,b,c))

In [ ]:
d=np.array([100,200])
np.vstack((a,d))

In [ ]:
d =np.array([100,200,300])
np.vstack((a,d))

In [ ]:
import numpy as np
a= np.arange(6).reshape(3,2)
a

In [ ]:
b=np.arange(10,19).reshape(3,3)
b

In [ ]:
np.hstack((a,b))

In [ ]:
c= np.array([[10,20],[30,40]])
c

In [ ]:
np.hstack((a,c))

In [ ]:
np.hstack((np.arange(3), np.arange(10,15)))

In [ ]:
import numpy as np
a=np.arange(6).reshape(3,2)
a

In [ ]:
b=np.arange(10,22).reshape(3,4)
b

In [ ]:
np.column_stack((a,b))

In [ ]:
np.hstack((a,b))

In [ ]:
x=np.array([1,2,3])
y=np.array([10,20,30])
np.column_stack((x,y))

In [ ]:
x[:, np.newaxis]

In [ ]:
y[: np.newaxis]

In [ ]:
x=np.array([1,2,3])
y=np.array([10,20,30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

In [ ]:
np.hstack((x,y))

In [ ]:
np.column_stack == np.hstack

In [ ]:
import numpy as np 

a = np.arange(6).reshape(2,3)

In [ ]:
b=np.arange(10,22).reshape(4,3)
b

In [ ]:
np.row_stack((a,b))

In [ ]:
np.vstack((a,b))

In [ ]:
a=np.array([4.,2.,1.])
b=np.array([3.,8.,7.])
print(np.row_stac((a,b)))

In [ ]:
print(np.vstack((a,b)))

In [ ]:
np.row_stack == np.vstack

In [ ]:
import numpy as np

a= np.array([1,2])
b=np.array([3,4])
c=np.array([5,6])

In [ ]:
np.concatenate((a,b,c))

In [ ]:
np.concatenate((a,b,c), axis=0)

In [ ]:
np.concatenate((a,b,c), axis=None)

In [ ]:
import numpy as np

x=np.arange(6).reshape(2,3)
x

In [ ]:
x=np.arange(10,16).reshape(2,3)
x

In [ ]:
z=np.arange(20,24).reshape(2,2)
z

In [ ]:
np.concatenate((x,y))

In [ ]:
np.concatenate((x,y,z))

In [ ]:
np.concatenate((x,y), axis=1)

In [ ]:
np.concatenate((x,y), axis=None)

In [ ]:
np.stack((a,b))

In [ ]:
np.stack((a,b), axis=1)

In [ ]:
np.stack((a,b), axis=-1)

In [ ]:
x=np.arange(6).reshape(2,3)
x

In [ ]:
y=np.arange(10,16).reshape(2,3)
y

In [ ]:
z=np.arange(20,26).reshape(2,3)
z

In [ ]:
ax0 = np.stack((x,y,z), axis=0)
ax0

In [ ]:
ax0.shape

In [ ]:
ax2 = np.stack((x,y,z), axis=z)
ax2

In [ ]:
ax0.shape

In [ ]:
x

In [ ]:
x[:, :, np.newaxis]

In [ ]:
np.expans_dims(x, axis=2)

In [ ]:
y

In [ ]:
y[:, :, np.newaxis]

In [ ]:
z

In [ ]:
np.expand_dims(z, axis=2)

In [ ]:
np.dtack((x,y,z), axis=2)

In [ ]:
import numpy as np 

a=np.arange(1,13).reshape(3, 4)
a

In [ ]:
c= np.arange(1,6,2)
c

In [ ]:
c[:,np.newaxis]

In [ ]:
np.hstack((a,c[:, np.newaxis]))

In [ ]:
np.hstack((a,c))

In [ ]:
np.hstack((a, np.expand_dims(c, axis=1)))

In [ ]:
np.column_stack((a,c))

In [ ]:
import numpy as np 

a=np.arange(1,13).reshape(3,4)
a

In [ ]:
b= np.arange(1,5)
b

In [ ]:
np.row_stack((a,b))

In [ ]:
np.vstack((a,b))

In [ ]:
import numpy as np 

a= np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
np.c_[a,b]

In [ ]:
np.column_stack((a,b))

In [ ]:
x=np.array([[1,2,3]])
y=np.array([[4,5,6]])

In [ ]:
np.c_[x,y]

In [ ]:
np.column_stack((x,y))

In [ ]:
np.c_[x, 10 ,20 ,Y]

In [ ]:
np.column_stack[x,10,20,y]

In [ ]:
import numpy as np
a= np.array([1,2,3])
b= np.array([4,5,6])

In [ ]:
np.r_[a,b]

In [ ]:
np.hstack((a,b))

In [ ]:
np.row_stack((a,b))

In [ ]:
np.r_[a,0,0,b]

In [ ]:
np.r_[3:10:3, [0]*2, 5,6]

In [ ]:
np.r_[-1:1:6j, [0]*2,5,6]

In [ ]:
np.linspace(-1,1,6)

In [ ]:
a=np.array([[0,1,2],[3,4,5]])
a

In [ ]:
np.r_[a,a,a]

In [ ]:
np.r['0',a,a]

In [ ]:
np.r_['-1',a,a]

In [ ]:
np.r_['1',a,a]

In [ ]:
np.r_['0,2', [1,2,3], [4,5,6]]

In [ ]:
np.r_['0,3,0',[1,2,3],[4,5,6]]

In [ ]:
np.r_['0,3,0',[1,2,3],[4,5,6]]

In [ ]:
np.r_['0,3,0',[1,2,3],[4,5,6]]

In [ ]:
np.r_['0,3,2',[1,2,3],[4,5,6]].shape

In [ ]:
np.r_['0,3,2',[1,2,3],[4,5,6]]

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a.shape)
print(b.shape)

In [ ]:
np.hstack((a,b))

In [ ]:
np,r_[a,b]

In [ ]:
np.comcatenate((a,b))

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a.shape)
print(b.shape)

In [ ]:
np.vstack((a,b))

In [ ]:
np.row_stack((a,b))

In [ ]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

In [ ]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a.shape)
print(b.shape)

In [ ]:
np.column_stack((a,b))

In [ ]:
np.hstack((a[:, np.newaxis], b[:, np,newaxis]))

In [ ]:
np.r_[a,b]

In [ ]:
np.concatenate(((a[:, np/newaxis], b[:,np.newaxis])), axis=1)

In [ ]:
import numpy as np 

x=np.arange(9.0)
x

In [ ]:
s=np.split(x,3)
s

In [ ]:
print(type(s))
print(s[0])

In [ ]:
np.split(x,4)

In [ ]:
x=np.arange(1,10)
x

In [ ]:
np.split(x, [2,6])
[array([1,2]),array([3,4,5,6]), array([7,8,9])]

In [ ]:
y=np.arange(10,61,10)
y

In [ ]:
np.split(y, [2,3,4])

In [ ]:
np.split(y, [2,3,4,6])

In [ ]:
y[4:6]

In [ ]:
y[6:]

In [ ]:
a=np.arange(24).reshape(2,12)
a

In [ ]:
np.split(a,3,axis=1)

In [ ]:
np.split(a,4,axis=1)

In [ ]:
np.split(a,5,axis=1)

In [ ]:
np.split(a, [3,5,7], axis=1)

In [ ]:
b=np.arange(24).reshape(6,4)
b

In [ ]:
np.split(b,3,axis=0)

In [ ]:
np.split(b, [2,4,6], axis=0)

In [ ]:
a=np.arange(10)
a

In [ ]:
np.hsplit(a,2)

In [ ]:
np.hsplit(a, [2,5])

In [ ]:
a=np.arange(24).reshape(2,12)
a

In [ ]:
np.hsplit(a,3)

In [ ]:
np.hsplit(a,4)

In [ ]:
np.hsplit(a,5)

In [ ]:
np.hsplit(a, (3,5,8))

In [ ]:
a[:, :3]

In [ ]:
a[:, 8:]

In [ ]:
a=np.arange(10)
a

In [ ]:
np.vsplit(a,2)

In [ ]:
a=np.arange(18).reshape(6,3)
a

In [ ]:
np.vsplit(a,3)

In [ ]:
np.vsplit(a,4)

In [ ]:
np.vsplit(a, (1,4,6))

In [ ]:
a[:1, :]

In [ ]:
a[4:6, :]

In [ ]:
a[6:, :]

In [ ]:
x=np.arange(32).redhape(4,4,2)
x

In [ ]:
np.hsplit(x,2)

In [ ]:
np.split(x,2,axis=1)

In [ ]:
x[:, :2, :]

In [ ]:
x[:, 2:, :]

In [ ]:
np.hsplit(x, [1,3])

In [ ]:
x=np.arange(32).reshape(4,4,2)
x

In [ ]:
np.vsplit(x,2)

In [ ]:
np.split(x,2,axis=0)

In [ ]:
x[:2, :, :]

In [ ]:
x[2:, :, :]

In [ ]:
np.vsplit(x, [1,3])

In [ ]:
import numpy as np

x=np.arange(9.0)
x

In [ ]:
np.array_split(x,2)

In [ ]:
np.array_split(x,3)

In [ ]:
np.array_split(x,4)

In [ ]:
np.array_split(x, [2,4,8])

In [ ]:
import numpy as np
a=np.arange(35).reshape(7,5)
a

In [ ]:
np.array_split(a, 2, axis=0)

In [ ]:
np.array_split(a,2,axis=1)

In [ ]:
np.array_split(a,4,axis=0)

In [ ]:
np.array_split(a,4,axis=1)

In [ ]:
np.array_split(a, [2,4], axis=0)

In [ ]:
np.array_split(a, [2,4], axis=1)

In [ ]:
import numpy as np

x=np.arange(24).reshape(2,2,6)
x

In [ ]:
np.array_split(x,4,axis=2)

In [ ]:
np.split(x, [2,4,5], axis=2)

In [ ]:
x[:, :, 5:]

In [ ]:
import numpy as np
x=np.arange(24).reshape(2,2,6)
x

In [ ]:
np.dsplit(x,2)

In [ ]:
np.dsplit(x,2)

In [ ]:
np.split(x,2,axis=2)

In [ ]:
np.dsplit(x,3)

In [ ]:
np.dsplit(x,4)

In [ ]:
np.dsplit(x, [2,4,5])

In [ ]:
x[:, :, 4:5]

In [ ]:
import numpy as np
rg=np.random.default_rng(12345)
rg

In [ ]:
r=rg.random()
r

In [ ]:
rg.random(5)

In [ ]:
rg.random((4,3))

In [ ]:
import numpy as np

rg=np.random.default_rng(12345)
r=rg.integers(low=0, high=10, size=3)
r

In [ ]:
rg.integers(1,7,(3,4))